"""add_history_1min

Revision ID: cbf119cd5ae6
Revises: c683721d9e18
Create Date: 2025-10-19 16:17:07.362366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbf119cd5ae6'
down_revision: Union[str, Sequence[str], None] = 'c683721d9e18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history_1min',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('date', sa.String(length=24), nullable=False, comment='取引日'),
    sa.Column('open', sa.Float(), nullable=True, comment='始値'),
    sa.Column('high', sa.Float(), nullable=True, comment='高値'),
    sa.Column('low', sa.Float(), nullable=True, comment='安値'),
    sa.Column('close', sa.Float(), nullable=True, comment='終値'),
    sa.Column('volume', sa.Float(), nullable=True, comment='出来高'),
    sa.Column('created_at', sa.String(length=24), nullable=True),
    sa.Column('updated_at', sa.String(length=24), nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['stock_info.symbol'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_history_1min_date'), 'history_1min', ['date'], unique=False)
    op.create_index(op.f('ix_history_1min_symbol'), 'history_1min', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_history_1min_symbol'), table_name='history_1min')
    op.drop_index(op.f('ix_history_1min_date'), table_name='history_1min')
    op.drop_table('history_1min')
    # ### end Alembic commands ###
